<?php

namespace App\Enums;

enum BookingStatus: string
{
    case PENDING_PJ_REVIEW = 'PENDING_PJ_REVIEW';
    case PENDING_KABAG_APPROVAL = 'PENDING_KABAG_APPROVAL';
    case APPROVED = 'APPROVED';
    case ALTERNATIVE_OFFERED = 'ALTERNATIVE_OFFERED';
    case CONFIRMED = 'CONFIRMED';
    case PREPARING = 'PREPARING';
    case IN_USE = 'IN_USE';
    case FINISHED_PENDING_INSPECTION = 'FINISHED_PENDING_INSPECTION';
    case COMPLETED = 'COMPLETED';
    case REJECTED = 'REJECTED';
    case CANCELLED = 'CANCELLED';
}
